version: '3'


services:

  app:
    build:
      context: .             # el dockerfile esta en la raiz en este caso
      target: ${STAGE}       #util para el multi-stage / camboio de dev a prod etc
      dockerfile: Dockerfile    #el archivo se llama Dockerfile 
    # command: yarn start:dev  
    volumes:
      - .:/app/             # bind volumes
      - /app/node_modules   # vol anonimo///para el caso d q no exista node_modules/ mapea el contenido del host
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET} 

  
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db:
    external: false




#docker compose up
#docker compose build
